name: permission_policy_example
description: Demonstrates how to use Permission policy.

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  permission_policy:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true