name: permission_policy
description: A flexible and powerful permission management system for Flutter applications with role-based access control, hierarchical permissions, and customizable UI components.
version: 3.2.1
homepage: https://nylo.dev
repository: https://github.com/nylo-core/permission-policy
issue_tracker: https://github.com/nylo-core/permission-policy/issues
funding:
  - https://github.com/sponsors/agordn52
topics:
  - roles
  - permissions
  - permissions-policy

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  nylo_support: ^7.27.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

screenshots:
  - description: The Nylo package logo.
    path: screenshots/logo.png

flutter: